<?php

use App\Http\Controllers\AdminContentController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminJournalController;
use App\Http\Controllers\AdminNewsController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\EmailVerificationController;
use App\Http\Controllers\GuideController;
use App\Http\Controllers\JournalSearchController;
use App\Http\Controllers\ModeratorController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RatingController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PageController::class, 'home'])->name('home');
Route::get('/reyting', [RatingController::class, 'index']);
Route::get('/baza', [PageController::class, 'base']);
Route::get('/api/jurnallar/qidiruv', JournalSearchController::class)->middleware(['auth', 'throttle:60,1'])->name('journals.search');
Route::get('/malumotnoma/{token}', [PageController::class, 'verify']);
Route::middleware('guest')->group(function () {
    Route::get('/royxat', [AuthController::class, 'showRegister']);
    Route::post('/royxat', [AuthController::class, 'register'])->middleware('throttle:10,1');
    Route::view('/tasdiq-kutilmoqda', 'auth.pending')->name('registration.pending');
    Route::get('/kirish', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/kirish', [AuthController::class, 'login'])->middleware('throttle:10,1');
    Route::get('/parolni-tiklash', [PasswordController::class, 'forgot']);
    Route::post('/parolni-tiklash', [PasswordController::class, 'send'])->middleware('throttle:5,1');
    Route::get('/parolni-tiklash/{token}', [PasswordController::class, 'showReset']);
    Route::post('/parolni-tiklash/yangi', [PasswordController::class, 'reset'])->middleware('throttle:10,1');
});
Route::middleware('auth')->group(function () {
    Route::post('/chiqish', [AuthController::class, 'logout']);
    Route::get('/bildirishnomalar', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/bildirishnomalar/hammasi-oqildi', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::post('/bildirishnomalar/{id}/oqildi', [NotificationController::class, 'markRead'])->whereUuid('id')->name('notifications.read');
    Route::get('/email/tasdiqlash', [EmailVerificationController::class, 'notice'])->name('verification.notice');
    Route::post('/email/tasdiqlash', [EmailVerificationController::class, 'resend'])->middleware('throttle:6,1')->name('verification.send');
    Route::get('/email/tasdiqlash/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware('signed')->name('verification.verify');
    Route::get('/profil', [ProfileController::class, 'edit'])->middleware('verified');
    Route::post('/profil', [ProfileController::class, 'update'])->middleware('verified');
    Route::get('/talaba/{user}', [ProfileController::class, 'show'])->middleware('verified');
    Route::get('/foto/{user}', [ProfileController::class, 'photo'])->middleware('verified');
    Route::get('/portfel', [ArticleController::class, 'portfolio'])->middleware('verified');
    Route::get('/yuklash', [ArticleController::class, 'create'])->middleware('verified');
    Route::post('/yuklash', [ArticleController::class, 'store'])->middleware(['verified', 'throttle:20,1']);
    Route::get('/maqola/{article}', [ArticleController::class, 'show'])->middleware('verified');
    Route::get('/maqola/{article}/pdf', [ArticleController::class, 'pdf'])->middleware('verified')->name('articles.pdf');
    Route::post('/malumotnoma', [PageController::class, 'certify'])->middleware('verified');
    Route::get('/jurnallar', [PageController::class, 'journals'])->name('journals.index');
    Route::get('/reyting/mening', [RatingController::class, 'my'])->name('ratings.my');
    Route::get('/reyting/eksport.csv', [RatingController::class, 'exportCsv'])->name('ratings.export.csv');
    Route::get('/yoriqnoma', [GuideController::class, 'index'])->name('guides.index');
    Route::get('/yoriqnoma/hujjat/{guide}', [GuideController::class, 'showGuide'])->name('guides.show');
    Route::get('/yoriqnoma/hujjat/{guide}/yuklab-olish', [GuideController::class, 'downloadGuide'])->name('guides.download');
    Route::get('/yoriqnoma/video/{video}', [GuideController::class, 'showVideo'])->name('videos.show');
    Route::get('/yoriqnoma/video/{video}/oqim', [GuideController::class, 'streamVideo'])->name('videos.stream');
    Route::get('/yoriqnoma/video/{video}/yuklab-olish', [GuideController::class, 'downloadVideo'])->name('videos.download');
    Route::get('/yangiliklar', [NewsController::class, 'index'])->name('news.index');
    Route::get('/yangiliklar/{news}/ilova', [NewsController::class, 'attachment'])->name('news.attachment');
    Route::get('/admin/yangiliklar', [AdminNewsController::class, 'index'])->name('admin.news.index');
    Route::get('/admin/yangiliklar/yangi', [AdminNewsController::class, 'create'])->name('admin.news.create');
    Route::post('/admin/yangiliklar', [AdminNewsController::class, 'store'])->name('admin.news.store');
    Route::get('/admin/yangiliklar/{news}/tahrir', [AdminNewsController::class, 'edit'])->name('admin.news.edit');
    Route::post('/admin/yangiliklar/{news}', [AdminNewsController::class, 'update'])->name('admin.news.update');
    Route::delete('/admin/yangiliklar/{news}', [AdminNewsController::class, 'destroy'])->name('admin.news.destroy');
    Route::get('/admin/yoriqnoma', [AdminContentController::class, 'guides'])->name('admin.guides.index');
    Route::post('/admin/yoriqnoma', [AdminContentController::class, 'storeGuide'])->name('admin.guides.store');
    Route::post('/admin/yoriqnoma/{guide}', [AdminContentController::class, 'updateGuide'])->name('admin.guides.update');
    Route::delete('/admin/yoriqnoma/{guide}', [AdminContentController::class, 'destroyGuide'])->name('admin.guides.destroy');
    Route::get('/admin/videolar', [AdminContentController::class, 'videos'])->name('admin.videos.index');
    Route::post('/admin/videolar', [AdminContentController::class, 'storeVideo'])->name('admin.videos.store');
    Route::post('/admin/videolar/{video}', [AdminContentController::class, 'updateVideo'])->name('admin.videos.update');
    Route::delete('/admin/videolar/{video}', [AdminContentController::class, 'destroyVideo'])->name('admin.videos.destroy');
    Route::get('/reyting/eksport.pdf', [RatingController::class, 'exportPdf'])->name('ratings.export.pdf');
    Route::get('/moderator/navbat', [ModeratorController::class, 'queue'])->name('moderator.queue');
    Route::get('/moderator/maqola/{article}', [ModeratorController::class, 'show'])->name('moderator.articles.show');
    Route::get('/moderator/maqola/{article}/sertifikat/pdf', [ModeratorController::class, 'certificatePdf'])->name('moderator.certificates.pdf');
    Route::post('/moderator/maqola/{article}/sertifikat', [ModeratorController::class, 'certificateDecision'])->name('moderator.certificates.decision');
    Route::get('/admin', [AdminController::class, 'index']);
    Route::get('/admin/audit', [AdminController::class, 'audit'])->name('admin.audit');
    Route::post('/admin/qaror/{article}', [AdminController::class, 'decide']);
    Route::post('/admin/import', [AdminController::class, 'import']);
    Route::post('/admin/sozlamalar', [AdminController::class, 'settings']);
    Route::get('/admin/foydalanuvchi/{user}/tahrir', [ProfileController::class, 'editUser']);
    Route::post('/admin/foydalanuvchi/{user}/tahrir', [ProfileController::class, 'updateUser']);
    Route::post('/admin/foydalanuvchi/{user}/tasdiq', [AdminController::class, 'approveUser'])->name('admin.users.approval');
    Route::post('/admin/foydalanuvchi/{user}', [AdminController::class, 'role']);
    Route::get('/admin/jurnallar', [AdminJournalController::class, 'index'])->name('admin.journals.index');
    Route::get('/admin/jurnallar/yangi', [AdminJournalController::class, 'create'])->name('admin.journals.create');
    Route::post('/admin/jurnallar/import-json', [AdminJournalController::class, 'importJson'])->name('admin.journals.import-json');
    Route::post('/admin/jurnallar', [AdminJournalController::class, 'store'])->name('admin.journals.store');
    Route::get('/admin/jurnallar/{journal}/tahrir', [AdminJournalController::class, 'edit'])->name('admin.journals.edit');
    Route::post('/admin/jurnallar/{journal}', [AdminJournalController::class, 'update'])->name('admin.journals.update');
    Route::post('/admin/jurnallar/{journal}/chiqarish', [AdminJournalController::class, 'delist'])->name('admin.journals.delist');
});
